@file:JvmName("KochavaConstants")

object Commands {
    const val COMMAND_KEY = "command_name"
    const val SEPARATOR = ","

    const val CONFIGURE = "configure"
    const val PURCHASE = "purchase"
    const val TUTORIAL_COMPLETE = "tutorialcomplete"
    const val LEVEL_COMPLETE = "levelcomplete"
    const val AD_VIEW = "adview"
    const val RATING = "rating"
    const val ADD_TO_CART = "addtocart"
    const val ADD_TO_WISH_LIST = "addtowishlist"
    const val CHECKOUT_START = "checkoutstart"
    const val SEARCH = "search"
    const val REGISTRATION_COMPLETE = "registrationcomplete"
    const val VIEW = "view"
    const val ACHIEVEMENT = "achievement"
    const val DEEP_LINK = "deeplink"
    const val SUBSCRIBE = "subscribe"
    const val START_TRIAL = "starttrial"
    const val SET_SLEEP = "setsleep"
}

object EventParameters {
    const val DEVICE_TYPE = "device_type"
    const val PLACEMENT = "placement"
    const val AD_TYPE = "ad_type"
    const val AD_CAMPAIGN_ID = "ad_campaign_id"
    const val AD_CAMPAIGN_NAME = "ad_campaign_name"
    const val AD_SIZE = "ad_size"
    const val AD_GROUP_NAME = "ad_group_name"
    const val AD_GROUP_ID = "ad_group_id"
    const val AD_NETWORK_NAME = "ad_network_name"
    const val AD_MEDIATION_NAME = "ad_mediation_name"
    const val CHECKOUT_AS_GUEST = "checkout_as_guest"
    const val CONTENT_ID = "content_id"
    const val CONTENT_TYPE = "content_type"
    const val CURRENCY = "currency"
    const val DATE = "date"
    const val DESCRIPTION = "description"
    const val DESTINATION = "destination"
    const val DURATION = "duration"
    const val SOURCE = "source"
    const val URI = "uri"
    const val COMPLETED = "completed"
    const val ACTION = "action"
    const val BACKGROUND = "background"
    const val SPATIAL_X = "spatial_x"
    const val SPATIAL_Y = "spatial_y"
    const val SPATIAL_Z = "spatial_z"
    const val VALIDATED = "validated"
    const val USER_NAME = "user_name"
    const val USER_ID = "user_id"
    const val SUCCESS = "success"
    const val START_DATE = "start_date"
    const val END_DATE = "end_date"
    const val SEARCH_TERM = "search_term"
    const val SCORE = "score"
    const val RESULTS = "results"
    const val REGISTRATION_METHOD = "registration_method"
    const val REFERRAL_FROM = "referral_from"
    const val RECEIPT_ID = "receipt_id"
    const val RATING_VALUE = "rating_value"
    const val QUANTITY = "quantity"
    const val PRICE = "price"
    const val ORIGIN = "origin"
    const val ORDER_ID = "order_id"
    const val NAME = "name"
    const val MAX_RATING_VALUE = "max_rating_value"
    const val LEVEL = "level"
    const val ITEM_ADDED_FROM = "item_added_from"
    const val SLEEP = "sleep"
    const val CUSTOM_PARAMETERS = "info_dictionary"
}

object Parameters {
    const val CONFIGURATION_PARAMS = "configuration_params"
    const val EVENT_PARAMS = "event_parameters"
}
